[[redirects]]
from = "https://rpint.netlify.app/*"
to = "https://www.tangruiping.com/:splat"
status = 301
force = true
[[redirects]]
from = "http://www.tangruiping.com/*"
to = "https://www.tangruiping.com/:splat"
status = 301
force = true